# # Where things are
# source: .
# destination: ./_site
# collections_dir: .
# plugins_dir: _plugins # takes an array of strings and loads plugins
# layouts_dir: _layouts
# data_dir: _data
# includes_dir: _includes
# sass: 
#   sass_dir: _sass
# collections: 
#   posts:
#     output: true
# gist:
#   noscript: false

# # Handling reading
# safe: true
# include: [".htaccess"]
# exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
# keep_files: [".git", ".svn"]
# encoding: "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# strict_front_matter: false

# # Filtering content
# show_drafts: null
# limit_posts: 0
# future: false
# unpublished: false

# # Plugins
# whitelist:
#   - jekyll-coffeescript
#   - jekyll-default-layout
#   - jekyll-gist
#   - jekyll-github-metadata
#   - jekyll-optional-front-matter
#   - jekyll-paginate
#   - jekyll-readme-index
#   - jekyll-titles-from-headings
#   - jekyll-relative-links
# plugins:
#   - jekyll-coffeescript
#   - jekyll-default-layout
#   - jekyll-gist
#   - jekyll-github-metadata
#   - jekyll-optional-front-matter
#   - jekyll-paginate
#   - jekyll-readme-index
#   - jekyll-titles-from-headings
#   - jekyll-relative-links

# # Conversion
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "/n/n"
# incremental: false

# # Serving
# detach: false
# port: 4000
# host: 127.0.0.1
# baseurl: ""  # Modifiez si votre site n'est pas à la racine
# show_dir_listing: false

# # Outputting
# permalink: date
# paginate_path: /page:num
# timezone: null

# quiet: false
# verbose: false
# defaults: []

# liquid:
#   error_mode: warn
#   strict_filters: false
#   strict_variables: false

# # Markdown processors
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     disable: true
#   auto_ids: true
#   entity_output: as_char
#   toc_levels: [1, 2, 3, 4, 5, 6]
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   input: GFM
#   hard_wrap: false
#   footnote_nr: 1
#   show_warnings: false

# # Ajoutez ces configurations de base
# title: [Nom de votre application]
# description: [Description de votre application]
# url: [URL de production]
# author: [Votre nom]