name: Déploiement automatique via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v4

      - name: Déploiement FTP
        uses: pontago/lftp-deploy-action@master
        with:
          protocol: sftp
          host: ftp.cluster021.hosting.ovh.net
          username: erpacfx
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./
          remote_dir: /www
