name: Déploiement automatique via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Déploiement FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster021.hosting.ovh.net
          username: erpacfx
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/
